trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
pool:
  vmImage: 'Ubuntu-16.04'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=10.x'
    displayName: 'Install Node.js'
  - script: |
      yarn install
    displayName: 'Install Dependencies'
  - script: |
      yarn build
    displayName: 'Build'
  - script: |
      yarn test:ci
    displayName: 'Test'
  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: 'junit.xml'
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'
  - task: PublishCodeCoverageResults@1
    inputs: 
      codeCoverageTool: Cobertura
      summaryFileLocation: 'coverage/cobertura-coverage.xml'
      reportDirectory: 'coverage'
    displayName: 'Publish Coverage Results'
  - script: |
      yarn dist
    displayName: 'Bundle'
  - task: Npm@1
    inputs:
      command: publish
      publishEndpoint: efoerster
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
    displayName: 'Publish to NPM'
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: latex-lsp
      repositoryName: latex-lsp/texlab
      assets: dist/texlab.js
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
    displayName: 'Publish to GitHub'
