trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*
pool:
  vmImage: 'Ubuntu-16.04'
steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '>=10.x'
    displayName: 'Install Node.js'
  - script: |
      yarn install
      yarn build
    displayName: 'Build'
  - script: |
      yarn test --coverage
    displayName: 'Test'
  - script: |
      npm install -g codecov    
      codecov
    env:
      CODECOV_TOKEN: $(codecovToken)
    displayName: 'Upload Test Report to Codecov'
  - script: |
      yarn dist
    displayName: 'Bundle'
  - task: GitHubRelease@0
    inputs:
      gitHubConnection: latex-lsp
      repositoryName: latex-lsp/texlab
      assets: dist/texlab.js
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags'))
    displayName: 'Publish to GitHub'
