[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.4.1"
license = "MIT"
readme = "README.md"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
    "crates/futures_boxed",
    "crates/jsonrpc", 
    "crates/jsonrpc_derive"]

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
citeproc = { git = "https://github.com/latex-lsp/citeproc", rev = "695a6205216ee15a4f1f899c03286ce9bddbe993" }
clap = "2.33"
copy_dir = "0.1.2"
futures-boxed = { path = "crates/futures_boxed" }
futures-preview = { version = "0.3.0-alpha.18", features = ["compat"] }
image = "0.22.1"
itertools = "0.8.0"
jsonrpc = { path = "crates/jsonrpc" }
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
log = "0.4.6"
lsp-types = { git = "https://github.com/latex-lsp/lsp-types", rev = "9fcc5d9b9d3013ce84e20ef566267754d594b268", features = ["proposed"] }
nom = "5.0.0"
once_cell = "0.2.6"
path-clean = "0.1.0"
regex = "1.2.1"
runtime = "0.3.0-alpha.4"
runtime-tokio = "0.3.0-alpha.4"
serde = { version = "1.0.99", features = ["derive", "rc"] }
serde_json = "1.0.40"
serde_repr = "0.1"
stderrlog = "0.4.1"
tempfile = "3"
tokio = "0.1"
tokio-codec = "0.1"
tokio-io = "0.1"
tokio-process = "0.2.4"
uuid = { version = "0.7", features = ["v4"] }
url = "2.0.0"
url_serde = "0.2.0"
walkdir = "2"

[dev-dependencies]
criterion = "0.2"
indoc = "0.3.4"

[[bench]]
name = "completion"
harness = false

[profile.release]
lto = true
