[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.2.0"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
    "crates/citeproc",
    "crates/jsonrpc", 
    "crates/jsonrpc_derive", 
    "crates/texlab_completion",
    "crates/texlab_completion_data",
    "crates/texlab_formatting",
    "crates/texlab_syntax",
    "crates/texlab_workspace",
    "scripts/build"]

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
clap = "2.33"
copy_dir = "0.1.2"
futures-boxed = { path = "crates/futures_boxed" }
futures-preview = { version = "0.3.0-alpha.17", features = ["compat"] }
html2md = "0.2.9"
image = "0.22.0"
itertools = "0.8.0"
jsonrpc = { path = "crates/jsonrpc" }
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
log = "0.4.6"
lsp-types = { git = "https://github.com/latex-lsp/lsp-types", rev = "9fcc5d9b9d3013ce84e20ef566267754d594b268", features = ["proposed"] }
nom = "5.0.0"
once_cell = "0.2.2"
path-clean = "0.1.0"
regex = "1.2.0"
runtime = "0.3.0-alpha.4"
runtime-tokio = "0.3.0-alpha.4"
serde = { version = "1.0.97", features = ["derive", "rc"] }
serde_json = "1.0.40"
serde_repr = "0.1"
stderrlog = "0.4.1"
tempfile = "3"
citeproc = { path = "crates/citeproc" }
texlab-completion = { path = "crates/texlab_completion" }
texlab-completion-data = { path = "crates/texlab_completion_data" }
texlab-formatting = { path = "crates/texlab_formatting" }
texlab-syntax = { path = "crates/texlab_syntax" }
texlab-workspace = { path = "crates/texlab_workspace" }
tokio = "0.1"
tokio-codec = "0.1"
tokio-process = "0.2.4"
tokio-stdin-stdout = "0.1"
url = "1.7.2"
url_serde = "0.2.0"
wait-timeout = "0.2.0"
walkdir = "2"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "completion"
harness = false

[profile.release]
lto = true