[package]
name = "texlab"
description = "LaTeX Language Server"
version = "1.6.0"
license = "MIT"
readme = "README.md"
authors = [
    "Eric Förster <efoerster@users.noreply.github.com>", 
    "Patrick Förster <pfoerster@users.noreply.github.com>"]
edition = "2018"

[workspace]
members = [
    "crates/futures_boxed",
    "crates/jsonrpc", 
    "crates/jsonrpc_derive"]

[dependencies]
base64 = "0.10.1"
bytes = "0.4.12"
clap = "2.33"
copy_dir = "0.1.2"
ducc = "0.1.0"
futures-boxed = { path = "crates/futures_boxed" }
futures-preview = "0.3.0-alpha.18"
html2md = "0.2.9"
image = "0.22.2"
itertools = "0.8.0"
jsonrpc = { path = "crates/jsonrpc" }
jsonrpc-derive = { path = "crates/jsonrpc_derive" }
log = "0.4.6"
lsp-types = { version = "0.61.0", features = ["proposed"] }
nom = "5.0.1"
once_cell = "1.2.0"
path-clean = "0.1.0"
petgraph = "0.4.13"
regex = "1.3.1"
serde = { version = "1.0.101", features = ["derive", "rc"] }
serde_json = "1.0.41"
serde_repr = "0.1"
stderrlog = "0.4.1"
tempfile = "3"
tokio = "0.2.0-alpha.5"
tokio-net = { version = "0.2.0-alpha.4", features = ["process"]}
uuid = { version = "0.7", features = ["v4"] }
url = "2.0.0"
url_serde = "0.2.0"
walkdir = "2"

[dev-dependencies]
criterion = "0.3"
indoc = "0.3.4"

[[bench]]
name = "completion"
harness = false

[profile.release]
lto = true
